version: '3'

services:
  db:
    image: postgres:alpine
    env_file:
      - ./env/dev.env
    volumes:
      - code:/tmp/pgdata
    ports:
      - "127.0.0.1:5432:5432"
#  web:
#    build: .
#    depends_on:
#      - db
#    restart: unless-stopped
#    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
#    env_file:
#      - ./env/dev.env
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"
#    entrypoint: /entrypoint.sh
#    links:
#      - db
volumes:
    code:
